// Generated by Wrangler on Sun Apr 14 2024 16:41:22 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	SYSTEM: KVNamespace;
	CONVERSATION: KVNamespace;
	API_KEY: "DummyKey";
	AI: unknown;
}
